services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: spring_boot_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
